FROM nginx
MAINTAINER "Shailesh Thakur"

# Copy the Configuration Code From Local To Nginx Container 

COPY sites-available/* /etc/nginx/sites-available/

RUN  ls -s /etc/nginx/sites-available/ /etc/nginx/sites-enabled/



